[package]
name = "Suitizen"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
suitizen =  "0x0"
sui =  "0000000000000000000000000000000000000000000000000000000000000002"
fungible_tokens = "0x0"
